#+TITLE: App Academy Scripts
This repository contains the scripts I wrote / adapted while studying
at App Academy.
* a/A Todos
~a/A Todos~ generates the daily tasks for App Academy. I use this to track
my work using Emacs ~org-mode~.

I use a custom todo keyword (~SCHD~), which others may wish to change to
~TODO~.

To run, enter ~ruby aa_todos.rb~ on the command line.
* Git Author Rewrite
~Git Author Rewrite~ is a bash script to change the email and author
information from the default for a/A computers to my own.

It is configured with my own name and email, and these should be
replaced before re-use.

To run, ~cd~ into the directory whose git history you want to modify, then
run ~bash $PATH/git-author-rewrite.sh~ on the command line, replacing
~$PATH~ with the path to wherever you've put the file on your own machine.

If you try to run the script twice for the same ~.git~ directory, you will
receive the following error:
: Cannot create a new backup.
: A previous backup already exists in refs/original/
: Force overwriting the backup with -f

In that case run the following command to remove the backup, and try
running the script again:
: rm -rf .git/refs/original
